# Generated by Django 5.2.4 on 2025-07-09 15:33

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to=store.models.user_profile_path),
        ),
    ]
