# Generated by Django 5.2.4 on 2025-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Easypaisa', 'Easypaisa'), ('JazzCash', 'JazzCash'), ('Bank Transfer', 'Bank Transfer')], default='Easypaisa', max_length=20),
        ),
    ]
